### ISSUE TITLE
Error using the script with kicad 7

### ISSUE THREAD

**Issue by cr1tbit** [yaqwsx/EasyEDAFootprintScraper#9]
Hey, thanks a lot for the script.

Had some problems that can be fixed by applying this simple patch

```
diff --git a/fetchComponent.py b/fetchComponent.py
index cd72349..cd05937 100755
--- a/fetchComponent.py
+++ b/fetchComponent.py
@@ -148,8 +148,8 @@ def postProcessFootprint(footprint):
     refPos = topMiddle(bbox) + pcbnew.wxPoint(0, -footprint.Reference().GetTextHeight())
     valuePos = bottomMiddle(bbox) + pcbnew.wxPoint(0, +footprint.Reference().GetTextHeight())
 
-    footprint.Reference().SetPosition(refPos)
-    footprint.Value().SetPosition(valuePos)
+    footprint.Reference().SetPosition(pcbnew.VECTOR2I(refPos.x, refPos.y))
+    footprint.Value().SetPosition(pcbnew.VECTOR2I(valuePos.x, valuePos.y))
 
     footprint.Reference().SetVisible(True)
     footprint.Value().SetVisible(True)
     
````
     
Most likely due to this: https://forum.kicad.info/t/kicad-7-scripting-position-errors/40719/3
     
After patching it seems to be working correctly.

**Comment by yaqwsx** [comment]
Applying the patch would make it incompatible with KiCAD 6.

Nevertheless, this project is-more-less abandoned a and there I well-maintained alternatives: https://github.com/uPesy/easyeda2kicad.py

**Comment by cr1tbit** [comment]
Might be worth to mention this in README, as I found this project via some article I googled, unaware of more up-to-date alternatives.

Thanks.
